version: '2'

services:
    jenkins:
        build:
            context: ./jenkins
        ports:
            - 8080:8080
        volumes:
            - jenkins:/var/jenkins_home
#            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - network
        environment:
            DOCKER_GID_ON_HOST: 0
        privileged: true
        restart: unless-stopped

    jenkins-slave:
        build:
            context: ./jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - jenkins-slave:/home/
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    jenkins:
        driver: local
    jenkins-slave:
        driver: local
